security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: auto

    providers:
        members:
            id: LeanpubBookClub\Infrastructure\Symfony\Security\MemberUserProvider
        admins:
            memory:
                users:
                    admin: { password: '%env(ADMIN_PASSWORD)%', roles: ['ROLE_ADMIN']}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        member_area:
            pattern: ^/member-area
            anonymous: lazy
            provider: members
            guard:
                authenticator:
                    - LeanpubBookClub\Infrastructure\Symfony\Security\AccessTokenAuthenticator
        admin_area:
            pattern: ^/admin-area
            http_basic:
                provider: admins
                realm: Admin area

    access_control:
        - { path: ^/member-area/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin-area, roles: ROLE_ADMIN }
        - { path: ^/member-area, roles: ROLE_MEMBER }
