talis_orm:
    aggregates:
        - LeanpubBookClub\Domain\Model\Purchase\Purchase
# TODO add mapping for these aggregates:
#        - LeanpubBookClub\Domain\Model\Session\Session
#        - LeanpubBookClub\Domain\Model\Member\Member
