twig:
    default_path: '%kernel.project_dir%/config/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    paths:
        '%kernel.project_dir%/config/assets/css': css
    globals:
        bookSummary: '@LeanpubBookClub\Infrastructure\Leanpub\BookSummary\BookSummary'
        site_title: '%env(SITE_TITLE)%'
