version: '3.4'

services:

    nginx:
        image: matthiasnoback/leanpub-book-club-production-nginx:latest
        build:
            dockerfile: docker/php/Dockerfile
            context: .
            target: symfony_nginx
        depends_on:
            - php
        networks:
            - traefik
            - internal
        # TODO uncomment when doing the actual deploy to production
        ports:
            - "80:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.readwiththeauthor_com_https.rule=Host(`readwiththeauthor.com`)"
            - "traefik.http.routers.readwiththeauthor_com_https.entrypoints=websecure"
            - "traefik.http.routers.readwiththeauthor_com_https.tls.certresolver=myhttpchallenge"

    php:
        image: matthiasnoback/leanpub-book-club-production-php:latest
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: symfony_php
            args:
                SYMFONY_VERSION: ${SYMFONY_VERSION:-}
                STABILITY: ${STABILITY:-stable}
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        environment:
            - SYMFONY_VERSION
        networks:
            - internal
        env_file:
            - .env.prod.local
        volumes:
            - var:/srv/app/var/

#
#    importer:
#        image: matthiasnoback/leanpub-book-club-production-php:latest
#        env_file:
#            - .env.prod.local
#        entrypoint: php bin/console leanpub:import-all-purchases --loop --delay=60
#        networks:
#            - internal

networks:
    traefik:
        external: true
    internal:

volumes:
    var:
