version: '3.4'

services:

    nginx:
        image: matthiasnoback/leanpub-book-club-production-nginx:latest
        build:
            dockerfile: docker/php/Dockerfile
            context: .
            target: symfony_nginx
        depends_on:
            - php

    php:
        image: matthiasnoback/leanpub-book-club-production-php:latest
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: symfony_php
            args:
                SYMFONY_VERSION: ${SYMFONY_VERSION:-}
                STABILITY: ${STABILITY:-stable}
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        environment:
            - SYMFONY_VERSION
        volumes:
            - var:/srv/app/var/

    importer:
        image: matthiasnoback/leanpub-book-club-production-php:latest
        command: php bin/console leanpub:import-all-purchases --loop --delay=60
        volumes:
            - var:/srv/app/var/
        depends_on:
            - php # it should start only after "php"'s entrypoint script has finished
        healthcheck:
            disable: true

volumes:
    var:
