version: '3.4'

services:

    nginx:
        ports:
            - "80:80"

    php:
        volumes:
            - .:/srv/app:cached
        depends_on:
            - mailhog
        env_file:
            - .env.local

    importer:
        volumes:
            - .:/srv/app:cached
        env_file:
            - .env.local

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
