version: '2.2'

services:
    php:
        image: matthiasnoback/leanpub-book-club-php:latest
        build: docker/php/
        volumes:
            - ./:/app:cached
            - ${COMPOSER_HOME}:/home/.composer:cached
        working_dir: /app
        user: ${HOST_UID}:${HOST_GID}
        environment:
            COMPOSER_HOME: "/home/.composer"
        env_file:
            - .env
            - .env.local

    nginx:
        image: matthiasnoback/leanpub-book-club-nginx:latest
        build: docker/nginx/
        volumes:
            - ./:/app:cached
        ports:
            - "80:80"
        depends_on:
          - php-fpm

    php-fpm:
        image: matthiasnoback/leanpub-book-club-php-fpm:latest
        build: docker/php-fpm/
        volumes:
            - ./:/app:cached
        env_file:
            - .env
            - .env.local
        user: ${HOST_UID}:${HOST_GID}
        depends_on:
          - mailhog

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
