version: '3.4'

services:

    nginx:
        container_name: readwiththeauthor_nginx
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.readwiththeauthor_com.rule=Host(`noback.readwiththeauthor.com`)"
            - "traefik.http.routers.readwiththeauthor_com.entrypoints=websecure"
            - "traefik.http.routers.readwiththeauthor_com.tls.certresolver=myhttpchallenge"
        networks:
            - internal
            - traefik
        restart: "unless-stopped"

    php:
        container_name: readwiththeauthor_php
        labels:
            - "traefik.enable=false"
        networks:
            - internal
        restart: "unless-stopped"
        env_file:
            - .env.prod.local

    importer:
        container_name: readwiththeauthor_importer
        labels:
            - "traefik.enable=false"
        networks:
            - internal
        restart: "unless-stopped"
        env_file:
            - .env.prod.local

networks:
    traefik:
        external: true
    internal:
