version: '2.2'

services:
    php:
        image: php:7.4-alpine
        volumes:
            - ./:/app:cached
        working_dir: /app
        user: ${HOST_UID}:${HOST_GID}
        env_file:
            - .env
            - .env.local

    composer:
        image: composer:latest
        volumes:
            - ./:/app:cached
            - ~/.composer:/tmp:cached
        user: ${HOST_UID}:${HOST_GID}

    nginx:
        image: matthiasnoback/leanpub-book-club-nginx:latest
        build: docker/nginx/
        volumes:
            - ./:/app:cached
        ports:
            - "80:80"
    php-fpm:
        image: matthiasnoback/leanpub-book-club-php-fpm:latest
        build: docker/php-fpm/
        volumes:
            - ./:/app:cached
