# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
#    App\:
#        resource: '../src/*'
#        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    LeanpubBookClub\Infrastructure\Symfony\Controller\:
        resource: '../src/LeanpubBookClub/Infrastructure/Symfony/Controller'
        tags: ['controller.service_arguments']

    LeanpubBookClub\Infrastructure\Symfony\Command\:
        resource: '../src/LeanpubBookClub/Infrastructure/Symfony/Command'

    LeanpubBookClub\Infrastructure\Symfony\Form\:
        resource: '../src/LeanpubBookClub/Infrastructure/Symfony/Form'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    LeanpubBookClub\Application\ApplicationInterface:
        factory: ['@LeanpubBookClub\Infrastructure\ProductionServiceContainer', 'application']
        public: true

    LeanpubBookClub\Infrastructure\ProductionServiceContainer:
        public: '%kernel.debug%'

    LeanpubBookClub\Infrastructure\Configuration:
        factory: ['LeanpubBookClub\Infrastructure\Configuration', 'createFromEnvironmentVariables']
        arguments:
            - '%kernel.project_dir%'

    LeanpubBookClub\Infrastructure\Symfony\SymfonyMailer:
        public: '%kernel.debug%'

    LeanpubBookClub\Domain\Model\Common\EmailAddress:
        factory: ['@LeanpubBookClub\Infrastructure\Configuration', 'systemEmailAddress']

    LeanpubBookClub\Infrastructure\Symfony\AddFlashMessageToSession:
        public: true

    LeanpubBookClub\Infrastructure\Symfony\Security\AccessTokenAuthenticator: ~

    LeanpubBookClub\Application\Members\Members: '@LeanpubBookClub\Application\ApplicationInterface'
    LeanpubBookClub\Infrastructure\Symfony\Security\MemberUserProvider: ~

    LeanpubBookClub\Domain\Model\Common\TimeZone:
        factory: ['@LeanpubBookClub\Infrastructure\Configuration', 'authorTimeZone']
